### ISSUE TITLE
Improve sponsor promotion

### ISSUE THREAD

**Issue by mattstein** [ddev/ddev.com-front-end#46]
#44 implied that we could be doing a better job of promoting project sponsors and acknowledging various levels of commitment.

I propose we do the following:

- Create/generate a `.svg` image to embed in the [`ddev/ddev` readme](https://github.com/ddev/ddev#wonderful-sponsors), so we can consistently use high-quality logos from the same source and fix abhorrent spacing issues that aren’t kind to any of them.
- Visually emphasize top-level sponsors on the ddev.com homepage, and possibly do the same thing with the readme.
- Again promote top-level sponsors globally in ddev.com’s footer, which has a lot of room for it.
- Identify any other opportunities within repositories, ddev.com, the docs, etc. that might tastefully promote sponsors without getting in the way of whatever the user/reader is doing.

Whatever “top-level” means, we should also update the [GitHub sponsors](https://github.com/sponsors/ddev) page to reflect a clear policy for this so it’s fair and always apparent where sponsor logos need to go.

**Comment by rfay** [comment]
Sounds great to me!

**Comment by rfay** [comment]
I think this one is all sorted out.  There's probably more we can do, can follow up in 
* #44

**Comment by rfay** [comment]
Thanks for the amazing work on this @mattstein !
