### ISSUE TITLE
New section: "DDEV Foundation"

### ISSUE THREAD

**Issue by rfay** [ddev/ddev.com-front-end#48]
We're on the cusp of being able to rename the Localdev Foundation to "DDEV Foundation", and then it really makes sense to have the modest documentation about it on ddev.com rather than localdev.foundation. Maybe a "Foundation" top-level page, or an addition to the "support" page?

**Comment by mattstein** [comment]
The support page is supposed to be the strongest, comprehensive collection of calls to action. Unless we’re encouraging people to ... join the foundation? ... I don’t think that’s the place for it.

Perhaps an expansion of the [about](https://ddev.com/about/) page that would cover it explicitly? (Will “DDEV Foundation” have its own dedicated domain?) This seems like exactly the place to elaborate on the people and organizations that are in charge of the project. Could mention sponsors, but that’s a separate issue and secondary in this context.

**Comment by rfay** [comment]
I did register "ddev.foundation", but now that things are moving along it seems more obvious to me to just incorporate explanation about it in ddev.com

Adding to the "about" page could certainly work.

**Comment by rfay** [comment]
Foundation page now exists, ddev.com/foundation
