### ISSUE TITLE
Request for RSS feed

### ISSUE THREAD

**Issue by rfay** [ddev/ddev.com-front-end#7]
@alberto64 contacted me via Twitter and asked that we enable an RSS feed on the ddev.com blog. I am surprised it's not there by default, and of course, that will be impacted by this ongoing work.

**Comment by mattstein** [comment]
This is done, just forgot to follow up. Both these feeds exist and are marked up as alternates:

- https://ddev.com/blog/rss.xml
- https://ddev.com/blog/feed.json
